# Generated by Django 3.2.11 on 2022-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0156_auto_20220407_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='today_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taggusermeta',
            name='background_gradient_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taggusermeta',
            name='tab_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationlinkwidget',
            name='link_type',
            field=models.CharField(choices=[('SPOTIFY', 'Spotify'), ('SOUNDCLOUD', 'Soundcloud'), ('APPLE_MUSIC', 'Apple Music'), ('APPLE_PODCAST', 'Apple Podcast'), ('POSHMARK', 'Poshmark'), ('DEPOP', 'Depop'), ('ETSY', 'Etsy'), ('SHOPIFY', 'Shopify'), ('AMAZON', 'Amazon'), ('ONLYFANS', 'Onlyfans'), ('AMAZON_AFFILIATE', 'Amazon Affiliate'), ('APP_STORE', 'App Store')], max_length=32),
        ),
        migrations.AlterField(
            model_name='genericlinkwidget',
            name='link_type',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('ARTICLE', 'Article'), ('DISCORD', 'Discord')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediawidget',
            name='link_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instrgam'), ('TWITTER', 'Twitter'), ('SNAPCHAT', 'Snapchat'), ('TIKTOK', 'Tiktok'), ('EMAIL', 'Email')], max_length=32),
        ),
    ]
