# Generated by Django 3.2.11 on 2022-05-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0157_auto_20220506_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagguser',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tagguser',
            name='image_background',
            field=models.ImageField(max_length=250, null=True, upload_to='mediafiles/'),
        ),
        migrations.AddField(
            model_name='tagguser',
            name='profile_image',
            field=models.ImageField(max_length=250, null=True, upload_to='mediafiles/'),
        ),
        migrations.AddField(
            model_name='tagguser',
            name='tier_icon',
            field=models.ImageField(max_length=250, null=True, upload_to='mediafiles/'),
        ),
    ]
