# Generated by Django 3.2.11 on 2022-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0158_auto_20220509_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagguser',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='applicationlinkwidget',
            name='link_type',
            field=models.CharField(choices=[('SPOTIFY', 'Spotify'), ('SOUNDCLOUD', 'Soundcloud'), ('APPLE_MUSIC', 'Apple Music'), ('APPLE_PODCAST', 'Apple Podcast'), ('POSHMARK', 'Poshmark'), ('DEPOP', 'Depop'), ('ETSY', 'Etsy'), ('SHOPIFY', 'Shopify'), ('AMAZON', 'Amazon'), ('ONLYFANS', 'Onlyfans'), ('VSCO', 'Vsco'), ('TIDAL', 'Tidal'), ('AMAZON_AFFILIATE', 'Amazon Affiliate'), ('APP_STORE', 'App Store')], max_length=32),
        ),
        migrations.AlterField(
            model_name='genericlinkwidget',
            name='link_type',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('ARTICLE', 'Article'), ('DISCORD', 'Discord'), ('EMAIL', 'Email'), ('DEEZER', 'Deezer')], max_length=32, null=True),
        ),
    ]
